export function help(): Record<string, unknown> {
  return {
    ok: true,
    usage: "gml <command> [options]",
    commands: [
      "auth login (--client-secret-file <path> | --client-id <id> [--client-secret <secret>]) [--scope full|readonly|metadata|modify|send|compose|insert|labels|settings.basic|settings.sharing]",
      "auth status",
      "auth logout",
      "profile",
      "labels [list]",
      "label-create <name>",
      "label-delete <name-or-id>",
      "label-rename <name-or-id> --to <new-name>",
      "list [query] [--max-results <n>] [--label <name-or-id>] [--include-spam-trash true|false]",
      "search <query>",
      "messages list [--q <query>] [--max-results <n>] [--page-token <token>] [--label-id <id>] [--include-spam-trash true|false]",
      "messages get <id> [--format full|minimal|raw|metadata] [--metadata-header <name>]",
      "read <id> [--raw]",
      "threads [query] [--max-results <n>]",
      "thread <id> [--format full|minimal|metadata]",
      "attachments <message-id>",
      "download <message-id> [--attachment <attachment-id>] [--out <dir>]",
      "send --to <addr> --subject <subject> (--body <body>|--body-file <path>|--text <body>) [--html] [--attach <path>] [--cc <addr>] [--bcc <addr>]",
      "reply <message-id> (--body <body>|--body-file <path>) [--all] [--html] [--attach <path>]",
      "forward <message-id> --to <addr> [--body <intro>|--body-file <path>] [--html] [--attach <path>] [--no-attachments]",
      "draft --to <addr> --subject <subject> (--body <body>|--body-file <path>) [--html] [--attach <path>]",
      "drafts [--max-results <n>]",
      "draft-send <draft-id>",
      "draft-delete <draft-id>",
      "modify <id...> [--query <q>] [--add <label>] [--remove <label>]",
      "trash|untrash|markread|markunread|star|unstar|archive|unarchive|spam|unspam <id...> [--query <q>]",
      "request <METHOD> <path> [--body <json>|--body-file <path>]",
    ],
  };
}
